/*
	MINEING SYSTEM FRAMEWORK
	Last Update - 8/9/2017
	Include Version - 0.1
	Created By: Amagida (2017)
*/


// stuff
#include <streamer>
#include <YSI\y_hooks>

#include "MINE\mineingutils.pwn"
#include "MINE\miningplayer.pwn"
/*
native CreateGoldStone(Float:x, Float:y, Float:z, name = 2);
native CreateNormalStone(Float:x, Float:y, Float:z, name = 1);
native SetStoneName(class, name[]);
native GetStoneDefaultName(class, out[], length = sizeof(out));
native GetStoneName(class, out[], length = sizeof(out));
native CreateStone(class, Float:x, Float:y, Float:z);
native DestroyStone(stoneid);
native IsValidStoneID(stoneid);
*/
